In [1]:
import numpy as np
#import library

create first array 

In [3]:
array1 = np.arange(15,41)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40])

In [ ]:
create second array

In [4]:
array2 = np.arange(10,26)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

they have different len

In [5]:
len(array1)>len(array2)

True

Create an array of all even integers from 2 to 20 and name it even_aaray1

In [8]:
even_aaray1 = np.arange(2,21,2)
even_aaray1 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

create an array of all even integers from 34 to 42 and name it even_array2

In [9]:
even_array2 = np.arange(34,43,2)
even_array2 

array([34, 36, 38, 40, 42])

Create a matrix of the two arrays using the stack function

In [13]:
my_first_array = [1,2]
my_second_array = [3,4]

In [14]:
np.stack([my_first_array,my_second_array],axis=1)

array([[1, 3],
       [2, 4]])

In [15]:
np.stack([my_first_array,my_second_array],axis=0)

array([[1, 2],
       [3, 4]])

In [ ]:
 Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column

In [23]:
my_matrix = np.array([np.random.randint(0,37) for i in range(36)]).reshape([6,6])
my_matrix

array([[21,  5, 22, 36,  1, 34],
       [34, 31, 36, 11, 35,  6],
       [24, 19,  6, 18, 12,  8],
       [ 8, 30, 17, 20, 16,  7],
       [ 0, 29,  8, 10, 29, 10],
       [32, 14,  0, 17, 25, 29]])

In [24]:
my_matrix[2,1]

19

Create a 5×2 matrix from a standard normal distribution generated with python.

In [31]:
my_norm_matrix = np.random.normal(0,1,10).reshape([5,2])
my_norm_matrix 

array([[ 0.26042366,  1.90007099],
       [ 0.08504465, -0.21929929],
       [-0.69194271, -0.01462335],
       [-0.97207113,  1.00801859],
       [ 0.48813172,  0.54244914]])

Retrieve the value intersecting the last row and the last column of your matrix

In [32]:
my_norm_matrix[-1,-1]

0.5424491412704973

Using your matrix created at 4.1, calculate the following:

a. minimum of the matrix

b. maximum of the matrix

c. standard deviation of the matrix

d. variance of the matrix

e. mean of the matrix

In [33]:
my_norm_matrix.min()

-0.9720711349502427

In [34]:
my_norm_matrix.max()

1.900070992409644

In [35]:
my_norm_matrix.std()

0.783362296021581

In [36]:
my_norm_matrix.var()

0.6136564868282032

In [37]:
my_norm_matrix.mean()

0.238620227395211